# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/chupina/CPP/Snake2

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/chupina/CPP/Snake2

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target package_source
package_source:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool for source..."
	/usr/bin/cpack --config ./CPackSourceConfig.cmake /home/chupina/CPP/Snake2/CPackSourceConfig.cmake
.PHONY : package_source

# Special rule for the target package_source
package_source/fast: package_source

.PHONY : package_source/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target package
package: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Run CPack packaging tool..."
	/usr/bin/cpack --config ./CPackConfig.cmake
.PHONY : package

# Special rule for the target package
package/fast: package

.PHONY : package/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chupina/CPP/Snake2/CMakeFiles /home/chupina/CPP/Snake2/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/chupina/CPP/Snake2/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named snake

# Build rule for target.
snake: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 snake
.PHONY : snake

# fast build rule for target.
snake/fast:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/build
.PHONY : snake/fast

Background.o: Background.cpp.o

.PHONY : Background.o

# target to build an object file
Background.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Background.cpp.o
.PHONY : Background.cpp.o

Background.i: Background.cpp.i

.PHONY : Background.i

# target to preprocess a source file
Background.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Background.cpp.i
.PHONY : Background.cpp.i

Background.s: Background.cpp.s

.PHONY : Background.s

# target to generate assembly for a file
Background.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Background.cpp.s
.PHONY : Background.cpp.s

Food.o: Food.cpp.o

.PHONY : Food.o

# target to build an object file
Food.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Food.cpp.o
.PHONY : Food.cpp.o

Food.i: Food.cpp.i

.PHONY : Food.i

# target to preprocess a source file
Food.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Food.cpp.i
.PHONY : Food.cpp.i

Food.s: Food.cpp.s

.PHONY : Food.s

# target to generate assembly for a file
Food.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Food.cpp.s
.PHONY : Food.cpp.s

Indice.o: Indice.cpp.o

.PHONY : Indice.o

# target to build an object file
Indice.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Indice.cpp.o
.PHONY : Indice.cpp.o

Indice.i: Indice.cpp.i

.PHONY : Indice.i

# target to preprocess a source file
Indice.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Indice.cpp.i
.PHONY : Indice.cpp.i

Indice.s: Indice.cpp.s

.PHONY : Indice.s

# target to generate assembly for a file
Indice.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Indice.cpp.s
.PHONY : Indice.cpp.s

Snake.o: Snake.cpp.o

.PHONY : Snake.o

# target to build an object file
Snake.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Snake.cpp.o
.PHONY : Snake.cpp.o

Snake.i: Snake.cpp.i

.PHONY : Snake.i

# target to preprocess a source file
Snake.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Snake.cpp.i
.PHONY : Snake.cpp.i

Snake.s: Snake.cpp.s

.PHONY : Snake.s

# target to generate assembly for a file
Snake.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/Snake.cpp.s
.PHONY : Snake.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/snake.dir/build.make CMakeFiles/snake.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... package_source"
	@echo "... rebuild_cache"
	@echo "... package"
	@echo "... edit_cache"
	@echo "... snake"
	@echo "... Background.o"
	@echo "... Background.i"
	@echo "... Background.s"
	@echo "... Food.o"
	@echo "... Food.i"
	@echo "... Food.s"
	@echo "... Indice.o"
	@echo "... Indice.i"
	@echo "... Indice.s"
	@echo "... Snake.o"
	@echo "... Snake.i"
	@echo "... Snake.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

